# Generated by Django 5.2.11 on 2026-02-09 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='service',
        #     name='description',
        # ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_class',
            field=models.CharField(help_text='Font Awesome class (e.g., fa-solid fa-pen-nib)', max_length=50),
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='agency.service')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
