# Generated by Django 5.2.11 on 2026-02-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_remove_service_description_service_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
